# Generated by Django 5.2.3 on 2025-06-21 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainwaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('wave1_data', models.JSONField()),
                ('wave2_data', models.JSONField()),
                ('sample_rate', models.IntegerField(default=256)),
                ('sequence_length', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('loss', models.FloatField()),
                ('training_samples', models.IntegerField()),
                ('validation_samples', models.IntegerField()),
                ('training_time', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('correspondence_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('prediction', models.BooleanField()),
                ('features', models.JSONField(default=dict)),
                ('brainwave_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='brainwave_analyzer.brainwavedata')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
